import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { Suspense } from "react";

import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";
import { MantineProvider } from "@mantine/core";
import Loading from "./loader";

const inter = Inter({
  variable: "--font-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Campers",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      data-theme="light"
      suppressHydrationWarning
    >
      <body className={`${inter.variable} antialiased`}>
        <MantineProvider defaultColorScheme="light">
          <TanStackProvider>
            <div className="layout">
              <Header />

              {/* Лоадер показується, коли щось усередині children “suspends” */}
              <Suspense fallback={<Loading />}>{children}</Suspense>

              <Toaster
                position="top-center"
                reverseOrder={false}
                toastOptions={{
                  style: {
                    borderRadius: "8px",
                    padding: "12px 16px",
                    fontSize: "16px",
                  },
                  duration: 5000,
                }}
              />
            </div>
          </TanStackProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
