import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Loading from "./loading";
import { Suspense } from "react";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";

const inter = Inter({
  variable: "--font-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Campers",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      data-theme="light"
      suppressHydrationWarning
    >
      <body className={`${inter.variable} antialiased`}>
        <TanStackProvider>
          <div className="layout">
            <Suspense fallback={<Loading />}>
              <Header />
              {children}
            </Suspense>
          </div>
        </TanStackProvider>
      </body>
    </html>
  );
}
